### PR TITLE
Executable fixes

### PR DESCRIPTION
**Pull request by Gskartwii**
Fixes the "Execute" permission missing from the binary files and adds a working freetype6.dll.

### CODE REVIEW

**Comment by Gskartwii** [comment]
I accidentally included the commit from #8. It shouldn't be too much of a hassle though.

**Comment by EgoMoose** [comment]
Just a heads up I had to replace your Roboto font. You unfortunately did not subtract from the decal id to get the images causing the image labels to error in some cases. I uploaded a fixed copy but I don't have the patience you do so it is only 4 styles.

**Comment by Gskartwii** [comment]
Ah, sorry about that. I could set up a script to scrape the proper IDs though.

**Comment by Gskartwii** [comment]
A little update on that; I did manage to scrape the IDs, and the updated script is available on my fork of this. Sadly I'm having issues with Roblox refusing to replicate the ModuleScript over the network due to it being too big. (> 1,5 MB) I might work something out though, maybe I'll split it to multiple ModuleScripts.

**Comment by EgoMoose** [comment]
I'll look into changing the font builder to split it up in the future. Are you sure the limit is 1.5 mb?

Side note:
Damn you Europeans and your weird comma decimals!

**Comment by Gskartwii** [comment]
I'm not sure what the limit is, but the script is a little over 1*,*5 MB which is too much.

**Pull request merged**
